spring:
  datasource:
    username: admin
    password: 12345
    url: jdbc:postgresql://localhost:10000/eCommerce
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  mail:
    host: smtp.gmail.com
    username: Meloonia52@gmail.com
    password: knxlunkzdwsfatxj #knxlunkzdwsfatxj
    port: 587
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
          ssl:
            required: true
            enabled: true

jwt:
  secretKey: "MySuperSecretKey"
  expirationTime: 1800000
